# Generated by Django 3.1.7 on 2021-04-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spring_api', '0004_auto_20210404_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('W', 'Woman'), ('O', 'Other'), ('P', 'Prefer not to say')], default=None, max_length=1, null=True),
        ),
    ]
