# Generated by Django 3.1.7 on 2021-04-04 23:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_spring_api', '0008_auto_20210404_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2, null=True),
        ),
    ]
